apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
  labels:
    app: tictactoe-service
spec:
  type: LoadBalancer
  selector:
    app: tictactoe-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
